### ISSUE TITLE
Mail Coif Circlet is worn by dukes outside of war and in civilian outfits despite having no aptitude for combat

### ISSUE THREAD

**Issue by voy178** [ElTyranos/CommunityFlavorPack#32] opened 2020-10-06 21:31 UTC
Same applies for many other coifs and hoods.

![20201006173639_1](https://user-images.githubusercontent.com/44323473/95261697-28705b00-082b-11eb-8c00-2d40b5a05ef6.jpg)
![20201006173646_1](https://user-images.githubusercontent.com/44323473/95261703-29a18800-082b-11eb-9ced-11a0874f9f69.jpg)
![20201006173655_1](https://user-images.githubusercontent.com/44323473/95261705-29a18800-082b-11eb-83f5-37efd53f1437.jpg)

**Comment by ElTyranos** [comment] 2020-10-06 22:10
@voy178 I have seen similar behaviour in vanilla games since 1.1 release.
Can you reproduce this ?

**Comment by voy178** [comment] 2020-10-06 22:24
Every game I start is the same. Seems to be linked to being a knight. Although women also have coifs despite not being able to participate in any battle by default.

**Comment by ElTyranos** [comment] 2020-10-06 22:26
The question is does it also happen in vanilla game without the mod ?
If yes : it's a bug from paradox
If no : it's a bug from me

**Comment by voy178** [comment] 2020-10-06 22:39
I booted up the game without mods and on a verified cache. I can confirm that all vassals (duke and under) except the marshal have civilian clothing while at peace regardless if they're knights or not. When at war, if they're knights, they change into war outfits as you'd expect. The same cannot be said when your mod is activated. Something is up with the mod.

**Comment by ElTyranos** [comment] 2020-10-07 05:38
Ok thanks, I will compare the code I must have missed something from 1.1.2 🤔

**Comment by ElTyranos** [comment] 2020-10-10 13:55
Fixed in 1.72

**Closed by ElTyranos** 2020-10-10 13:55 UTC
Labels: bug, testing required
