### ISSUE TITLE
The new bonnets are not used?

### ISSUE THREAD

**Issue by voy178** [ElTyranos/CommunityFlavorPack#73] opened 2021-01-17 23:54 UTC
I have yet to see any Iberian lady wear the low and high nobility bonnets. Males do but rarely. Common bonnets appear somewhat frequently for both males and females.

Is it possible that they're bugged or not implemented properly?

**Comment by ElTyranos** [comment] 2021-01-18 13:08
What is your game current date ?
if you're in 1066 (right after game start), there are no iberian duchies but Portugal. On top of that, most counties are held by the kings as they are only a few. The hats should start to appear when your game will have more duchies and  counties held by Iberians.

**Comment by voy178** [comment] 2021-01-18 13:14
Ca 1300. I've played the game throughout from start with your mod as Castille while preserving the other traditional Iberian kingdoms including Portugal with different Iberian cultured vassals of all ranks. (I theme my playthroughs after your updates to appreciate them <3)

Most either wear nothing if they're counts. Some male dukes do wear the bonnet but rarely. Their spouses prefer other headgear like crowns.

**Comment by ElTyranos** [comment] 2021-01-18 13:16
Could you please, with character browser and "iberian culture" filter, send me pics of your Iberian characters ordered by rank so I can have a estimation of the ratios ?

Or simply send me your savegame so I can use it myself to tweak the attribution ratios.

**Comment by voy178** [comment] 2021-01-18 13:36
I didn't take a pic of everything, it's too much but as you can see, only male dukes wear bonnets sometimes but more often crowns, and only unlanded or married to unlanded females wear the bonnet of the common variant. Mayors wear common bonnets the most. Trust me, I've checked everything, they're just not there.

![20210118142847_1](https://user-images.githubusercontent.com/44323473/104921692-f29a5100-5999-11eb-8f3e-8a909597b4f0.jpg)
![20210118142850_1](https://user-images.githubusercontent.com/44323473/104921695-f332e780-5999-11eb-924a-d085376ea3b4.jpg)
![20210118142853_1](https://user-images.githubusercontent.com/44323473/104921698-f332e780-5999-11eb-8258-e16444edb172.jpg)
![20210118142856_1](https://user-images.githubusercontent.com/44323473/104921700-f3cb7e00-5999-11eb-9efe-ad51f626b98d.jpg)
![20210118142900_1](https://user-images.githubusercontent.com/44323473/104921701-f3cb7e00-5999-11eb-9b12-909f15e04a31.jpg)
![20210118142903_1](https://user-images.githubusercontent.com/44323473/104921703-f4641480-5999-11eb-974a-e828e946b43e.jpg)
![20210118142906_1](https://user-images.githubusercontent.com/44323473/104921704-f4641480-5999-11eb-85a6-d3ed1e20e08b.jpg)
![20210118142915_1](https://user-images.githubusercontent.com/44323473/104921705-f4641480-5999-11eb-952d-aa6907f1c588.jpg)
![20210118142918_1](https://user-images.githubusercontent.com/44323473/104921707-f4fcab00-5999-11eb-8eb2-271551f72973.jpg)
![20210118142950_1](https://user-images.githubusercontent.com/44323473/104921660-ed3d0680-5999-11eb-8185-e40d99bb6102.jpg)
![20210118142954_1](https://user-images.githubusercontent.com/44323473/104921664-ee6e3380-5999-11eb-81ad-a59c5c2d72c0.jpg)
![20210118142957_1](https://user-images.githubusercontent.com/44323473/104921665-ee6e3380-5999-11eb-85ad-9073e5b11d6f.jpg)
![20210118143000_1](https://user-images.githubusercontent.com/44323473/104921667-ef06ca00-5999-11eb-8dab-e9a22167e754.jpg)
![20210118143003_1](https://user-images.githubusercontent.com/44323473/104921668-ef06ca00-5999-11eb-81ce-8f9c371ea08a.jpg)
![20210118143006_1](https://user-images.githubusercontent.com/44323473/104921669-ef9f6080-5999-11eb-8d86-bea4e3dfeefa.jpg)
![20210118143008_1](https://user-images.githubusercontent.com/44323473/104921671-ef9f6080-5999-11eb-8299-018fa6adb70a.jpg)
![20210118143011_1](https://user-images.githubusercontent.com/44323473/104921672-ef9f6080-5999-11eb-9b08-726b01fa7c14.jpg)
![20210118143013_1](https://user-images.githubusercontent.com/44323473/104921673-f037f700-5999-11eb-9451-288b258d9569.jpg)
![20210118143015_1](https://user-images.githubusercontent.com/44323473/104921674-f037f700-5999-11eb-8d16-91deafaf8595.jpg)
![20210118143027_1](https://user-images.githubusercontent.com/44323473/104921678-f0d08d80-5999-11eb-8f1d-5b421ec44c5e.jpg)
![20210118143029_1](https://user-images.githubusercontent.com/44323473/104921679-f0d08d80-5999-11eb-800d-fc946a5e77b1.jpg)
![20210118143031_1](https://user-images.githubusercontent.com/44323473/104921681-f1692400-5999-11eb-8a28-ef76ac5bfcd1.jpg)
![20210118143033_1](https://user-images.githubusercontent.com/44323473/104921682-f1692400-5999-11eb-831b-0a677ebeda06.jpg)
![20210118142824_1](https://user-images.githubusercontent.com/44323473/104921684-f1692400-5999-11eb-89ff-4fd4e00b87e1.jpg)
![20210118142829_1](https://user-images.githubusercontent.com/44323473/104921687-f201ba80-5999-11eb-8176-b5e4da4f3505.jpg)
![20210118142840_1](https://user-images.githubusercontent.com/44323473/104921690-f201ba80-5999-11eb-931f-bc007b045c61.jpg)
![20210118142844_1](https://user-images.githubusercontent.com/44323473/104921691-f29a5100-5999-11eb-930f-0b5211d58bcf.jpg)

**Comment by ElTyranos** [comment] 2021-01-18 14:19
Can you please send me your savegame (from `Documents\Paradox Interactive\Crusader Kings III\save games`) ?

**Comment by voy178** [comment] 2021-01-18 15:55
Not possible, too large for GitHub. But it's not like you can't replicate it. If you see but one low or high bonnet for females, you can debunk this as a problem with my game.

**Comment by ElTyranos** [comment] 2021-01-19 13:11
[01_headgear.txt](https://github.com/ElTyranos/CommunityFlavorPack/files/5836035/01_headgear.txt)

Could you please try with these parameters in your current game ? I had to cheat to reproduce a full iberian spain, I'm not sure  the result is consistent with a  regular game.

Just overwrite this file in `\steamapps\workshop\content\1158310\2220098919\gfx\portraits\portrait_modifiers`

**Comment by voy178** [comment] 2021-01-19 14:32
Well it had an affect. A handful of characters now wear bonnets, mostly spouses, but the vast majority still prefer crowns, trait/skill specific clothing, veils/wimples/barbettes or mostly nothing. Also, the Iberian grandmasters wear the bonnet too sometimes which doesn't go well with the tabard, but what to do.

So I tried a new game to see if that would help more. Cheated my way to more land, landed Castilian Christian adults and waited until most got married. The result was that many more dukes wore the bonnets which was nice to see, so did their duchesses, although it's kind of weird to see the mishmash of crown/bonnet couples. The counts continued to wear nothing, but their spouses certainly wore more bonnets, but not the majority, I also saw one countess wearing the common bonnet which must have been a mistake and a rarity at that. So really, it was a success apart from the hatless counts. I would keep the high probability of wearing bonnets though, makes them stand out from the Western Europe crowd. Here's a save file.

[githubtestiberia.zip](https://github.com/ElTyranos/CommunityFlavorPack/files/5836473/githubtestiberia.zip)

![20210119152652_1](https://user-images.githubusercontent.com/44323473/105047772-0d88c600-5a6b-11eb-8f2d-3bd565243598.jpg)
![20210119152659_1](https://user-images.githubusercontent.com/44323473/105047773-0eb9f300-5a6b-11eb-9e4a-cd928dce0043.jpg)
![20210119152704_1](https://user-images.githubusercontent.com/44323473/105047774-0f528980-5a6b-11eb-8677-78a7b9b321b3.jpg)
![20210119152708_1](https://user-images.githubusercontent.com/44323473/105047775-0f528980-5a6b-11eb-984d-784580d44e14.jpg)
![20210119152712_1](https://user-images.githubusercontent.com/44323473/105047776-0feb2000-5a6b-11eb-9734-145ab5d0573d.jpg)
![20210119152716_1](https://user-images.githubusercontent.com/44323473/105047778-0feb2000-5a6b-11eb-9946-83eac77645c2.jpg)
![20210119152720_1](https://user-images.githubusercontent.com/44323473/105047782-1083b680-5a6b-11eb-85ae-3f13f1e62ef1.jpg)
![20210119152345_1](https://user-images.githubusercontent.com/44323473/105047451-a23ef400-5a6a-11eb-8559-7fbbc15e78f9.jpg)

**Comment by ElTyranos** [comment] 2021-01-19 18:00
Ok the issue is that I copy paster "western_low_nobles" which has a typo. 
None of the western counts had a hat either so it bugged me. Checked the code aaaaand... Well done PDX.

Fixing all this.

**Comment by ElTyranos** [comment] 2021-01-19 18:02
Regarding the mismatch between spouses, there's nothing I can do, the probability is computed per character, I have no way to check if spouse wears an iberian hat or not.

**Comment by voy178** [comment] 2021-01-19 18:02
Glad to have been of help...? I completely understand the limitations, I'm just reporting what I see.

**Comment by ElTyranos** [comment] 2021-01-19 18:04
I did the report to paradox aswell, but CFP  will have the fix while they update : https://forum.paradoxplaza.com/forum/threads/ck-iii-01_headgear-txt-typo.1452988/

I'll also try to fix the helmets assigned to characters who are not at war.

**Comment by voy178** [comment] 2021-01-19 18:11
I tried your fix and indeed they were stuff now which is such a relief and looks much better... however, I think this revealed even more potential bugs. The gear they can wear doesn't match their clothes, like silk instead of the low noble variant and in different colours than their own stuff. Regardless, thanks for fixing it!

**Comment by ElTyranos** [comment] 2021-01-19 19:08
The  fix on PDX forum is for vanilla code, I also fixed  CFP categories and they will all work in the hotfix. Thank you for your inputs !

**Closed** 2021-01-19 21:37 UTC
Labels: testing required
